"""initial_schema_users_teams_participants

Revision ID: 3c059318c96d
Revises: 
Create Date: 2026-09-19 23:46:17.774906

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c059318c96d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_name', sa.String(length=255), nullable=False),
    sa.Column('current_round_number', sa.Integer(), nullable=False),
    sa.Column('current_round_name', sa.String(length=255), nullable=False),
    sa.Column('current_round_status', sa.String(length=50), nullable=False),
    sa.Column('table_count', sa.Integer(), nullable=False),
    sa.Column('is_mock_enabled', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teams',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('team_number', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('assigned_table', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('REGISTERED', 'CHECKED_IN', 'ACTIVE', 'ELIMINATED', 'DISQUALIFIED', name='team_status_enum', create_constraint=True), nullable=False),
    sa.Column('current_round', sa.Integer(), nullable=False),
    sa.Column('is_qualified_for_next_round', sa.Boolean(), nullable=False),
    sa.Column('total_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teams_team_number'), 'teams', ['team_number'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ORGANIZER', 'MARSHAL', 'JUDGE', 'PUBLIC_PROJECTOR', name='user_role_enum', create_constraint=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('participants',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('usn', sa.String(length=50), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('role', sa.Enum('LEADER', 'MEMBER', name='participant_role_enum', create_constraint=True), nullable=False),
    sa.Column('checked_in', sa.Boolean(), nullable=False),
    sa.Column('checked_in_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('team_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_participants_team_id'), 'participants', ['team_id'], unique=False)
    op.create_index(op.f('ix_participants_usn'), 'participants', ['usn'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_participants_usn'), table_name='participants')
    op.drop_index(op.f('ix_participants_team_id'), table_name='participants')
    op.drop_table('participants')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_teams_team_number'), table_name='teams')
    op.drop_table('teams')
    op.drop_table('event_settings')
    # ### end Alembic commands ###
