"""add_rounds_and_scoring_models

Revision ID: 96d9541ddc93
Revises: 3c059318c96d
Create Date: 2026-09-20 00:15:03.899114

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96d9541ddc93'
down_revision: Union[str, None] = '3c059318c96d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('round_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('codename', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('initial_teams_count', sa.Integer(), nullable=False),
    sa.Column('qualifying_teams_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('is_finalized', sa.Boolean(), nullable=False),
    sa.Column('finalized_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finalized_by', sa.String(length=255), nullable=True),
    sa.Column('config_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('finale_agent_verdicts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('team_id', sa.String(length=36), nullable=False),
    sa.Column('suspected_agent', sa.String(length=255), nullable=True),
    sa.Column('actual_agent', sa.String(length=255), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('bonus_points', sa.Float(), nullable=True),
    sa.Column('penalty_points', sa.Float(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('verified_by', sa.String(length=255), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_finale_agent_verdicts_team_id'), 'finale_agent_verdicts', ['team_id'], unique=True)
    op.create_table('finale_scorecards',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('team_id', sa.String(length=36), nullable=False),
    sa.Column('judge_name', sa.String(length=255), nullable=False),
    sa.Column('scores_json', sa.JSON(), nullable=False),
    sa.Column('total_score', sa.Float(), nullable=True),
    sa.Column('is_complete', sa.Boolean(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('last_edited_by', sa.String(length=255), nullable=True),
    sa.Column('last_edited_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_finale_scorecards_team_id'), 'finale_scorecards', ['team_id'], unique=True)
    op.create_table('round1_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('team_id', sa.String(length=36), nullable=False),
    sa.Column('mini_rounds_json', sa.JSON(), nullable=False),
    sa.Column('raw_total_seconds', sa.Float(), nullable=True),
    sa.Column('total_penalty_seconds', sa.Float(), nullable=False),
    sa.Column('adjusted_total_seconds', sa.Float(), nullable=True),
    sa.Column('fastest_mini_round_seconds', sa.Float(), nullable=True),
    sa.Column('is_complete', sa.Boolean(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('qualification_status', sa.String(length=50), nullable=False),
    sa.Column('tie_requires_review', sa.Boolean(), nullable=False),
    sa.Column('tie_reason', sa.String(length=255), nullable=True),
    sa.Column('hidden_code_recovered', sa.Boolean(), nullable=False),
    sa.Column('hidden_code_recovered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('hidden_code_notes', sa.Text(), nullable=True),
    sa.Column('last_edited_by', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_round1_records_team_id'), 'round1_records', ['team_id'], unique=True)
    op.create_table('round2_placements',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('game_number', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.String(length=36), nullable=False),
    sa.Column('placement', sa.Integer(), nullable=False),
    sa.Column('points', sa.Float(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('recorded_by', sa.String(length=255), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_number', 'team_id', name='uq_round2_game_team')
    )
    op.create_index(op.f('ix_round2_placements_team_id'), 'round2_placements', ['team_id'], unique=False)
    op.create_table('round3_code_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('team_id', sa.String(length=36), nullable=False),
    sa.Column('fragments_json', sa.JSON(), nullable=False),
    sa.Column('is_complete', sa.Boolean(), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified_by', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_round3_code_records_team_id'), 'round3_code_records', ['team_id'], unique=True)
    op.create_table('round3_transactions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('team_id', sa.String(length=36), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('organizer_ref', sa.String(length=255), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_reversed', sa.Boolean(), nullable=False),
    sa.Column('reversal_transaction_id', sa.String(length=36), nullable=True),
    sa.Column('reversed_transaction_id', sa.String(length=36), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_round3_transactions_team_id'), 'round3_transactions', ['team_id'], unique=False)
    op.create_table('round4_agent_guesses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('team_id', sa.String(length=36), nullable=False),
    sa.Column('outcome', sa.String(length=50), nullable=False),
    sa.Column('points_awarded', sa.Float(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('verified_by', sa.String(length=255), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_round4_agent_guesses_team_id'), 'round4_agent_guesses', ['team_id'], unique=True)
    op.create_table('round4_judge_scores',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('judge_id', sa.String(length=100), nullable=False),
    sa.Column('judge_name', sa.String(length=255), nullable=False),
    sa.Column('team_id', sa.String(length=36), nullable=False),
    sa.Column('scores_json', sa.JSON(), nullable=False),
    sa.Column('total_score', sa.Float(), nullable=False),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_submitted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('judge_id', 'team_id', name='uq_round4_judge_team')
    )
    op.create_index(op.f('ix_round4_judge_scores_judge_id'), 'round4_judge_scores', ['judge_id'], unique=False)
    op.create_index(op.f('ix_round4_judge_scores_team_id'), 'round4_judge_scores', ['team_id'], unique=False)
    op.create_table('round4_pairs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('pair_number', sa.Integer(), nullable=False),
    sa.Column('team_a_id', sa.String(length=36), nullable=True),
    sa.Column('team_b_id', sa.String(length=36), nullable=True),
    sa.Column('is_confirmed', sa.Boolean(), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmed_by', sa.String(length=255), nullable=True),
    sa.Column('case_id', sa.String(length=100), nullable=True),
    sa.Column('case_name', sa.String(length=255), nullable=True),
    sa.Column('case_details', sa.Text(), nullable=True),
    sa.Column('team_a_side', sa.String(length=100), nullable=False),
    sa.Column('team_b_side', sa.String(length=100), nullable=False),
    sa.Column('team_a_has_case_file', sa.Boolean(), nullable=False),
    sa.Column('team_a_case_file_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('team_a_has_opposing_file', sa.Boolean(), nullable=False),
    sa.Column('team_a_opposing_file_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('team_b_has_case_file', sa.Boolean(), nullable=False),
    sa.Column('team_b_case_file_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('team_b_has_opposing_file', sa.Boolean(), nullable=False),
    sa.Column('team_b_opposing_file_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stages_json', sa.JSON(), nullable=False),
    sa.Column('resource_person_name', sa.String(length=255), nullable=True),
    sa.Column('resource_person_notes', sa.Text(), nullable=True),
    sa.Column('resource_person_questions_json', sa.JSON(), nullable=False),
    sa.Column('is_questioning_complete', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['team_a_id'], ['teams.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['team_b_id'], ['teams.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pair_number')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('round4_pairs')
    op.drop_index(op.f('ix_round4_judge_scores_team_id'), table_name='round4_judge_scores')
    op.drop_index(op.f('ix_round4_judge_scores_judge_id'), table_name='round4_judge_scores')
    op.drop_table('round4_judge_scores')
    op.drop_index(op.f('ix_round4_agent_guesses_team_id'), table_name='round4_agent_guesses')
    op.drop_table('round4_agent_guesses')
    op.drop_index(op.f('ix_round3_transactions_team_id'), table_name='round3_transactions')
    op.drop_table('round3_transactions')
    op.drop_index(op.f('ix_round3_code_records_team_id'), table_name='round3_code_records')
    op.drop_table('round3_code_records')
    op.drop_index(op.f('ix_round2_placements_team_id'), table_name='round2_placements')
    op.drop_table('round2_placements')
    op.drop_index(op.f('ix_round1_records_team_id'), table_name='round1_records')
    op.drop_table('round1_records')
    op.drop_index(op.f('ix_finale_scorecards_team_id'), table_name='finale_scorecards')
    op.drop_table('finale_scorecards')
    op.drop_index(op.f('ix_finale_agent_verdicts_team_id'), table_name='finale_agent_verdicts')
    op.drop_table('finale_agent_verdicts')
    op.drop_table('round_states')
    # ### end Alembic commands ###
