"""add_registration_submissions_and_settings

Revision ID: e8464c1e0f9b
Revises: 96d9541ddc93
Create Date: 2026-09-21 20:32:07.193218

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8464c1e0f9b'
down_revision: Union[str, None] = '96d9541ddc93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registration_submissions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('external_submission_id', sa.String(length=255), nullable=False),
    sa.Column('team_name', sa.String(length=255), nullable=False),
    sa.Column('leader_name', sa.String(length=255), nullable=False),
    sa.Column('leader_usn', sa.String(length=100), nullable=False),
    sa.Column('leader_email', sa.String(length=255), nullable=False),
    sa.Column('leader_phone', sa.String(length=50), nullable=True),
    sa.Column('members_count', sa.Integer(), nullable=False),
    sa.Column('consent_given', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_team_id', sa.String(length=36), nullable=True),
    sa.Column('raw_payload', sa.JSON(), nullable=False),
    sa.Column('auto_approved', sa.Boolean(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['created_team_id'], ['teams.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_registration_submissions_external_submission_id'), 'registration_submissions', ['external_submission_id'], unique=True)
    op.add_column('event_settings', sa.Column('registration_auto_approve', sa.Boolean(), server_default=sa.text('0'), nullable=False))
    op.add_column('event_settings', sa.Column('webhook_secret', sa.String(length=255), server_default=sa.text("''"), nullable=False))
    op.add_column('event_settings', sa.Column('public_registration_open', sa.Boolean(), server_default=sa.text('1'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event_settings', 'public_registration_open')
    op.drop_column('event_settings', 'webhook_secret')
    op.drop_column('event_settings', 'registration_auto_approve')
    op.drop_index(op.f('ix_registration_submissions_external_submission_id'), table_name='registration_submissions')
    op.drop_table('registration_submissions')
    # ### end Alembic commands ###
