import { FormEvent, useEffect, useMemo, useState } from 'react';
import { ArrowLeft, KeyRound, LockKeyhole, ShieldCheck } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { LiveShell, Mark } from './LiveShell';
import { getSession, request } from './eventApi';

type Account = { login_id: string; display_name: string; role: 'SUPER_ADMIN' | 'ADMIN' | 'PARTICIPANT'; is_active: boolean };

export function AccountManagementPage() {
  const [accounts, setAccounts] = useState<Account[]>([]); const [role, setRole] = useState<Account['role']>('ADMIN'); const [target, setTarget] = useState(''); const [currentPassword, setCurrentPassword] = useState(''); const [newPassword, setNewPassword] = useState(''); const [confirmPassword, setConfirmPassword] = useState(''); const [reason, setReason] = useState('Credential update'); const [error, setError] = useState(''); const [notice, setNotice] = useState(''); const [busy, setBusy] = useState(false); const nav = useNavigate();
  useEffect(() => { if (getSession()?.role !== 'SUPER_ADMIN') { nav('/login', { replace: true }); return; } request<Account[]>('/control/accounts').then(items => { setAccounts(items); setTarget(items.find(item => item.role === 'ADMIN')?.login_id || ''); }).catch(item => setError(item.message)); }, []);
  const choices = useMemo(() => accounts.filter(account => account.role === role), [accounts, role]);
  useEffect(() => { if (choices.length && !choices.some(item => item.login_id === target)) setTarget(choices[0].login_id); }, [choices, target]);
  async function submit(event: FormEvent) { event.preventDefault(); if (newPassword !== confirmPassword) { setError('The new password entries do not match.'); return; } setBusy(true); setError(''); setNotice(''); try { const response = await request<{ login_id: string }>('/control/accounts/password', 'POST', { current_super_password: currentPassword, target_login_id: target, new_password: newPassword, new_password_confirmation: confirmPassword, reason }); setNotice(`Password changed for ${response.login_id}.`); setCurrentPassword(''); setNewPassword(''); setConfirmPassword(''); } catch (item) { setError(item instanceof Error ? item.message : 'Password update failed.'); } finally { setBusy(false); } }
  return <LiveShell><main className="mobile-page"><header className="topbar live-reveal"><Mark/><button onClick={() => nav('/control')} aria-label="Back to Round 1"><ArrowLeft size={18}/></button></header><section className="agent-card live-reveal"><div className="agent-orbit"><KeyRound size={32}/></div><div className="eyebrow"><ShieldCheck size={14}/> SUPER ADMIN ONLY</div><h1>Manage <span>logins.</span></h1><p>Choose an account and set a new password. Password values are never shown or saved in the audit log.</p><form onSubmit={submit}><label>Account type<select value={role} onChange={event => setRole(event.target.value as Account['role'])}><option value="SUPER_ADMIN">Super admins</option><option value="ADMIN">Admins</option><option value="PARTICIPANT">Teams</option></select></label><label>Login account<select value={target} onChange={event => setTarget(event.target.value)}>{choices.map(account => <option value={account.login_id} key={account.login_id}>{account.login_id} · {account.display_name}</option>)}</select></label><label>Current super-admin password<div className="input-icon"><LockKeyhole size={17}/><input type="password" value={currentPassword} onChange={event => setCurrentPassword(event.target.value)} autoComplete="current-password" required /></div></label><label>New password<input type="password" minLength={8} value={newPassword} onChange={event => setNewPassword(event.target.value)} autoComplete="new-password" required /></label><label>Confirm new password<input type="password" minLength={8} value={confirmPassword} onChange={event => setConfirmPassword(event.target.value)} autoComplete="new-password" required /></label><label>Reason<input value={reason} onChange={event => setReason(event.target.value)} minLength={3} required /></label><button className="primary-button" disabled={busy || !target}>{busy ? 'Saving...' : <>Update password <KeyRound size={17}/></>}</button></form>{(error || notice) && <div className={`toast ${error ? 'toast-error' : ''}`}>{error || notice}</div>}</section></main></LiveShell>;
}
