import { FormEvent, useEffect, useRef, useState } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { Check, Compass, Instagram, LogOut, ScanLine, Send, ShieldAlert, Sparkles, UserRoundCheck, X } from 'lucide-react';
import gsap from 'gsap';
import instagramQr from '../assets/asymptotes-instagram-qr.png';
import { LiveShell, Mark } from './LiveShell';
import { clearSession, getSession, request } from './eventApi';

type State = { complete: boolean; checkpoint: number; round_started: boolean; riddle?: string; is_scanned?: boolean; attempts_used?: number; is_locked?: boolean; instagram?: string; secret_agent_submitted: boolean; rank?: number | null; qualified?: boolean; completed_at?: string | null };
type Feedback = { kind: 'scan' | 'correct' | 'wrong' | 'finish'; text: string; id: number };

export function ParticipantPage() {
  const [state, setState] = useState<State | null>(null); const [answer, setAnswer] = useState(''); const [agentName, setAgentName] = useState(''); const [notice, setNotice] = useState(''); const [error, setError] = useState(''); const [sending, setSending] = useState(false); const [feedback, setFeedback] = useState<Feedback | null>(null);
  const { location } = useParams(); const navigate = useNavigate(); const reveal = useRef<HTMLDivElement>(null); const feedbackRef = useRef<HTMLDivElement>(null);
  const showFeedback = (kind: Feedback['kind'], text: string) => setFeedback({ kind, text, id: Date.now() });
  const redirectIfEliminated = (message: string) => { if (message.includes('Round 1 has ended')) { clearSession(); navigate('/results', { replace: true, state: { message } }); return true; } return false; };
  const load = async () => { try { setState(await request<State>('/participant/state')); } catch (e) { const message = e instanceof Error ? e.message : 'Unable to load event.'; if (!redirectIfEliminated(message)) setError(message); } };
  useEffect(() => { if (getSession()?.role !== 'PARTICIPANT') { navigate('/login', { replace: true }); return; } void load(); }, []);
  useEffect(() => { if (!location || !getSession()) return; (async () => { try { const data = await request<State>('/participant/scan', 'POST', { location: Number(location) }); setState(data); setNotice('Location verified. Enter the envelope answer exactly.'); showFeedback('scan', 'STATION VERIFIED'); } catch (e) { const message = e instanceof Error ? e.message : 'Scan failed.'; if (!redirectIfEliminated(message)) { setError(message); showFeedback('wrong', 'SCAN NOT ACCEPTED'); } } finally { navigate('/play', { replace: true }); } })(); }, [location]);
  useEffect(() => { if (!feedbackRef.current || window.matchMedia('(prefers-reduced-motion: reduce)').matches) return; const ctx = gsap.context(() => { gsap.fromTo(feedbackRef.current, { autoAlpha: 0, scale: .78, rotate: -3 }, { autoAlpha: 1, scale: 1, rotate: 0, duration: .38, ease: 'back.out(1.9)' }); gsap.fromTo('.feedback-spark', { scale: .3, autoAlpha: 0 }, { scale: 1, autoAlpha: 1, duration: .45, stagger: .06, ease: 'power3.out' }); }, feedbackRef); const timer = window.setTimeout(() => setFeedback(null), feedback?.kind === 'finish' ? 2300 : 1400); return () => { ctx.revert(); window.clearTimeout(timer); }; }, [feedback?.id]);
  useEffect(() => { if (!state?.riddle || state.checkpoint === 1 || !reveal.current || window.matchMedia('(prefers-reduced-motion: reduce)').matches) return; gsap.fromTo(reveal.current, { autoAlpha: 0, y: 18 }, { autoAlpha: 1, y: 0, duration: .45, ease: 'power3.out' }); }, [state?.checkpoint, state?.riddle]);
  async function nominateAgent(e: FormEvent) { e.preventDefault(); if (!agentName.trim() || sending) return; setSending(true); setError(''); try { const data = await request<State>('/participant/secret-agent', 'POST', { agent_name: agentName }); setState(data); setNotice('Secret Agent saved confidentially. Your hunt is ready.'); showFeedback('correct', 'AGENT CONFIRMED'); } catch (err) { setError(err instanceof Error ? err.message : 'Unable to save Secret Agent.'); } finally { setSending(false); } }
  async function submit(e: FormEvent) { e.preventDefault(); if (!answer || sending) return; setSending(true); setError(''); try { const result = await request<{ correct: boolean; state: State }>('/participant/answer', 'POST', { answer }); setState(result.state); if (result.correct) { const finished = result.state.complete; setNotice(finished ? 'Your time has been recorded. Please wait for results.' : 'Correct. Your next clue is ready.'); showFeedback(finished ? 'finish' : 'correct', finished ? 'ROUND 01 COMPLETE' : 'CLUE UNLOCKED'); setAnswer(''); } else { setNotice('Not accepted. Check capitals, spaces, and hyphens.'); showFeedback('wrong', 'TRY AGAIN'); } } catch (err) { const message = err instanceof Error ? err.message : 'Unable to submit.'; if (!redirectIfEliminated(message)) { setError(message); showFeedback('wrong', 'NOT ACCEPTED'); } } finally { setSending(false); } }
  const logout = () => { clearSession(); navigate('/login'); };
  const feedbackIcon = feedback?.kind === 'wrong' ? <X size={38}/> : <Check size={38}/>;
  return <LiveShell><main className="mobile-page participant-page"><header className="topbar live-reveal"><Mark /><button aria-label="Sign out" onClick={logout}><LogOut size={18}/></button></header>
    {feedback && <div className={`feedback-overlay ${feedback.kind}`} aria-live="polite"><div ref={feedbackRef} className="feedback-core">{[0, 1, 2, 3, 4].map(i => <Sparkles className="feedback-spark" key={i} />)}<div className="feedback-icon">{feedbackIcon}</div><strong>{feedback.text}</strong></div></div>}
    {!state ? <div className="load-card live-reveal">Loading your event...</div> : !state.secret_agent_submitted ? <section className="agent-card live-reveal"><div className="agent-orbit"><UserRoundCheck size={34}/></div><div className="eyebrow"><Sparkles size={14}/> CONFIDENTIAL TEAM STEP</div><h1>Choose the <span>Secret Agent.</span></h1><p>Enter one member’s name. This is stored only for the super-admin team and can be submitted once.</p><form onSubmit={nominateAgent}><label>Secret Agent name<input value={agentName} onChange={e => setAgentName(e.target.value)} maxLength={120} placeholder="MEMBER NAME" required /></label><button className="primary-button" disabled={sending}>{sending ? 'Saving...' : <>Confirm confidentially <UserRoundCheck size={17}/></>}</button></form></section> : state.complete ? <section className="finish-card live-reveal"><div className="finish-icon"><Check size={30}/></div><div className="eyebrow">ROUND 01 COMPLETE</div><h1>Your time is <span>recorded.</span></h1><p>Please take a break. The qualified teams will be announced on Instagram.</p><img className="instagram-qr" src={instagramQr} alt="Instagram QR for ASYMPTOTES_BMSIT"/><div className="insta-handle"><Instagram size={20}/>@ASYMPTOTES_BMSIT</div></section> : <>
      <section className="progress-line live-reveal"><span className="active">0{state.checkpoint}</span><i /><span>03</span><small>MINI ROUND {state.checkpoint}</small></section>
      {!state.round_started ? <section className="event-card live-reveal"><Compass size={28}/><h2>Stand by at the start point.</h2><p>The event will unlock when a super admin starts the round.</p></section> : state.is_locked ? <section className="event-card danger live-reveal"><ShieldAlert size={28}/><h2>Checkpoint paused</h2><p>Please speak to the nearest event volunteer.</p></section> : !state.is_scanned ? <section className="event-card clue-card live-reveal" ref={reveal}><ScanLine size={30}/><div className="eyebrow">LOCATION CHECK</div><h1>{state.checkpoint === 1 ? 'Use your physical first clue.' : 'Your next clue.'}</h1>{state.checkpoint > 1 && <p className="riddle">{state.riddle}</p>}<p className="subnote">When you arrive, scan only the QR displayed at that location.</p></section> : <section className="answer-card live-reveal"><div className="eyebrow"><Check size={14}/> LOCATION VERIFIED</div><h1>Enter the final answer.</h1><p>It must match exactly: capitals, spaces, and hyphens matter.</p><form onSubmit={submit}><input value={answer} onChange={e => setAnswer(e.target.value)} autoCorrect="off" autoCapitalize="off" spellCheck="false" placeholder="TYPE ANSWER" autoFocus/><button className="primary-button" disabled={!answer || sending}>{sending ? 'Checking...' : <>Submit <Send size={17}/></>}</button></form></section>}
      {(notice || error) && <div className={`toast live-reveal ${error ? 'toast-error' : ''}`}>{error || notice}</div>}
    </>}</main></LiveShell>;
}
