import { FormEvent, useEffect, useMemo, useState } from 'react';
import { ArrowLeft, CheckCircle2, Lock, Play, RefreshCw, ShieldCheck, Trophy, Users } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { LiveShell, Mark } from './LiveShell';
import { getSession, request } from './eventApi';

type Player = { participant_id: string; participant_name: string; team_identifier: string; team_name: string; seat_position: number; outcome: 'WIN' | 'LOSS' | null; base_points: number | null };
type CaboTable = { table_number: number; admin_login_id: string | null; admin_name: string | null; players: Player[]; complete: boolean };
type Standing = { team_id: string; team_identifier: string; team_name: string; r1_rank: number | null; r1_points: number; cabo_points: number; rank_award: number; rank: number | null; total_points: number };
type Control = { generated: boolean; finalized: boolean; tables: CaboTable[]; standings: Standing[]; award_scale: number[] };

function StaffHeader({ back }: { back: string }) { const nav = useNavigate(); return <header className="topbar live-reveal"><Mark/><button onClick={() => nav(back)} aria-label="Back"><ArrowLeft size={18}/></button></header>; }

export function Round2SuperPage() {
  const [data, setData] = useState<Control | null>(null); const [assignments, setAssignments] = useState<Record<number, string>>({}); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const nav = useNavigate();
  const load = () => request<Control>('/r2/control/overview').then(item => { setData(item); setAssignments(Object.fromEntries(item.tables.map(table => [table.table_number, table.admin_login_id || '']))); }).catch(item => setError(item.message));
  useEffect(() => { if (getSession()?.role !== 'SUPER_ADMIN') { nav('/login', { replace: true }); return; } void load(); }, []);
  const admins = useMemo(() => [...new Set(data?.tables.map(table => table.admin_login_id).filter(Boolean) || [])] as string[], [data]);
  async function generate() { setBusy(true); setError(''); try { await request('/r2/control/generate', 'POST', {}); await load(); } catch (item) { setError(item instanceof Error ? item.message : 'Unable to generate tables.'); } finally { setBusy(false); } }
  async function saveAssignments() { const grouped = Object.entries(assignments).reduce<Record<string, number[]>>((result, [table, admin]) => { if (admin) (result[admin] ||= []).push(Number(table)); return result; }, {}); const payload = Object.entries(grouped).map(([admin_login_id, table_numbers]) => ({ admin_login_id, table_numbers })); setBusy(true); setError(''); try { await request('/r2/control/assign-admins', 'POST', { assignments: payload }); await load(); } catch (item) { setError(item instanceof Error ? item.message : 'ADMIN01–ADMIN03 need three tables; ADMIN04–ADMIN08 need two.'); } finally { setBusy(false); } }
  async function applyAwards() { if (!window.confirm('Apply the 80-to-0 ranking awards using the current Cabo standings?')) return; setBusy(true); setError(''); try { await request('/r2/control/apply-rank-awards', 'POST', {}); await load(); } catch (item) { setError(item instanceof Error ? item.message : 'Could not apply awards.'); } finally { setBusy(false); } }
  async function finalize() { if (!window.confirm('Finalize Round 2? Admin score entry will be locked.')) return; setBusy(true); setError(''); try { await request('/r2/control/finalize', 'POST', {}); await load(); } catch (item) { setError(item instanceof Error ? item.message : 'Could not finalize Round 2.'); } finally { setBusy(false); } }
  return <LiveShell><main className="mobile-page super-admin-console r2-super-console"><StaffHeader back="/control"/><section className="staff-hero live-reveal super-console-hero"><div className="eyebrow"><ShieldCheck size={14}/> SUPER ADMIN · ROUND 02</div><h1>Cabo <span>control.</span></h1><p>Nineteen tables. Five members each. The 16 qualifiers play with TEAM1005, TEAM1009, and TEAM1019; no table includes two members of the same team.</p><div className="super-console-actions">{!data?.generated && <button className="primary-button" onClick={generate} disabled={busy}><Play size={17}/>{busy ? 'Generating...' : 'Generate 19 Cabo tables'}</button>}<button className="icon-refresh" onClick={load}><RefreshCw size={16}/> Refresh</button>{data?.generated && !data.finalized && <><button className="primary-button" onClick={applyAwards} disabled={busy}><Trophy size={17}/> Apply 80 → 0 rank awards</button><button className="danger-button" onClick={finalize} disabled={busy}><Lock size={16}/> Finalize Round 2</button></>}</div></section>{error && <div className="toast toast-error">{error}</div>}{data?.generated && <><section className="control-summary live-reveal"><div><Users size={18}/><strong>{data.tables.length}/19</strong><span>tables</span></div><div><CheckCircle2 size={18}/><strong>{data.tables.filter(table => table.complete).length}/19</strong><span>scored</span></div></section><section className="r2-note live-reveal"><strong>Admin allocation</strong><p>ADMIN01–ADMIN03 each receive three tables. ADMIN04–ADMIN08 each receive two. Change a table’s admin below only if the same 3/3/3/2/2/2/2/2 split is retained.</p><button className="icon-refresh" onClick={saveAssignments} disabled={busy}>Save table assignments</button></section><section className="r2-table-grid live-reveal">{data.tables.map(table => <article className="r2-table-card" key={table.table_number}><div className="table-title"><b>TABLE {String(table.table_number).padStart(2, '0')}</b><span>{table.complete ? 'SCORED' : 'OPEN'}</span></div><label>Assigned admin<select value={assignments[table.table_number] || ''} onChange={event => setAssignments(current => ({ ...current, [table.table_number]: event.target.value }))}>{admins.map(admin => <option value={admin} key={admin}>{admin}</option>)}</select></label>{table.players.map(player => <div className="r2-player" key={player.participant_id}><span>{player.participant_name}</span><small>{player.team_identifier}</small></div>)}</article>)}</section><section className="r2-standings live-reveal"><div className="eyebrow"><Trophy size={14}/> PRIVATE LEADERBOARD</div><h2>Round 2 standings</h2>{data.standings.map((team, index) => <article key={team.team_id}><b>#{team.rank || index + 1} {team.team_identifier}</b><span>{team.team_name}</span><small>Cabo {team.cabo_points >= 0 ? '+' : ''}{team.cabo_points} · award +{team.rank_award} · total {team.total_points}</small></article>)}</section></>}</main></LiveShell>;
}

export function Round2AdminPage() {
  const [data, setData] = useState<{ available: boolean; finalized: boolean; tables: CaboTable[] } | null>(null); const [outcomes, setOutcomes] = useState<Record<string, 'WIN' | 'LOSS'>>({}); const [error, setError] = useState(''); const [notice, setNotice] = useState(''); const [busy, setBusy] = useState(false); const nav = useNavigate();
  const load = () => request<{ available: boolean; finalized: boolean; tables: CaboTable[] }>('/r2/admin/tables').then(item => { setData(item); setOutcomes(Object.fromEntries(item.tables.flatMap(table => table.players.filter(player => player.outcome).map(player => [player.participant_id, player.outcome!] )))); }).catch(item => setError(item.message));
  useEffect(() => { if (getSession()?.role !== 'ADMIN') { nav('/login', { replace: true }); return; } void load(); }, []);
  async function save(table: CaboTable, event: FormEvent) { event.preventDefault(); setBusy(true); setError(''); setNotice(''); try { await request(`/r2/admin/tables/${table.table_number}/scores`, 'POST', { scores: table.players.map(player => ({ participant_id: player.participant_id, outcome: outcomes[player.participant_id] })) }); setNotice(`Table ${table.table_number} scores saved.`); await load(); } catch (item) { setError(item instanceof Error ? item.message : 'Select WIN or LOSS for all five players.'); } finally { setBusy(false); } }
  return <LiveShell><main className="mobile-page"><StaffHeader back="/station"/><section className="staff-hero live-reveal"><div className="eyebrow"><Users size={14}/> ADMIN · ROUND 02</div><h1>Your Cabo <span>tables.</span></h1><p>Record one WIN or LOSS result for every player at your assigned tables. Team totals update automatically.</p><button className="icon-refresh" onClick={load}><RefreshCw size={16}/> Refresh</button></section>{error && <div className="toast toast-error">{error}</div>}{notice && <div className="toast">{notice}</div>}{data && !data.available && <section className="event-card live-reveal"><Lock size={28}/><h2>Awaiting assignment.</h2><p>The super admin will generate Round 2, then assign two or three tables depending on your admin role.</p></section>}{data?.tables.map(table => <section className="answer-card live-reveal r2-score-card" key={table.table_number}><div className="eyebrow">TABLE {String(table.table_number).padStart(2, '0')}</div><h2>{table.complete ? 'Saved results' : 'Enter results'}</h2><form onSubmit={event => save(table, event)}>{table.players.map(player => <label className="score-row" key={player.participant_id}><span><b>{player.participant_name}</b><small>{player.team_identifier} · {player.team_name}</small></span><select disabled={data.finalized} value={outcomes[player.participant_id] || ''} onChange={event => setOutcomes(current => ({ ...current, [player.participant_id]: event.target.value as 'WIN' | 'LOSS' }))}><option value="">Result</option><option value="WIN">WIN · +40</option><option value="LOSS">LOSS · −40</option></select></label>)}<button className="primary-button" disabled={busy || data.finalized}>{data.finalized ? 'Round 2 locked' : busy ? 'Saving...' : 'Save this table'}</button></form></section>)}</main></LiveShell>;
}
