import { FormEvent, useEffect, useState } from 'react';
import { CheckCircle2, Download, LogOut, MapPin, Play, RefreshCw, RotateCcw, ShieldCheck, Unlock, Users, X } from 'lucide-react';
import QRCode from 'qrcode';
import { useNavigate } from 'react-router-dom';
import { LiveShell, Mark } from './LiveShell';
import { clearSession, downloadReportPdf, getSession, request } from './eventApi';

type StationTeam = { team_identifier: string; team_name: string; checkpoint: number; set: string; complete: boolean; attempts: number; is_current: boolean; scanned: boolean; last_answer: string | null };
type Station = { location: number; location_name: string; teams: StationTeam[] };
type ControlTeam = { team_identifier: string; team_name: string; checkpoint: number; complete: boolean; attempts: number; location: number | null; set: string; last_answer: string | null; points: number; secret_agent_name: string | null; rank: number | null; qualified: boolean; completed_at: string | null };
type Control = { started: boolean; qualifier_limit: number; qualified_count: number; teams: ControlTeam[] };

function Header() { const nav = useNavigate(); return <header className="topbar live-reveal"><Mark/><button onClick={() => { clearSession(); nav('/login'); }} aria-label="Sign out"><LogOut size={18}/></button></header>; }
const stamp = (value: string | null) => value ? new Date(value).toLocaleString('en-IN', { dateStyle: 'short', timeStyle: 'medium' }) : '—';

export function AdminPage() {
  const [data, setData] = useState<Station | null>(null); const [qr, setQr] = useState(''); const [error, setError] = useState(''); const nav = useNavigate();
  const load = () => request<Station>('/admin/station').then(setData).catch(error => setError(error.message));
  useEffect(() => { if (getSession()?.role !== 'ADMIN') nav('/login', { replace: true }); else void load(); }, []);
  useEffect(() => { if (!data?.location) return; QRCode.toDataURL(`${window.location.origin}/scan/${data.location}`, { width: 360, margin: 1, color: { dark: '#1b1110', light: '#fff4ef' } }).then(setQr).catch(() => setError('Unable to prepare the station QR.')); }, [data?.location]);
  return <LiveShell><main className="mobile-page"><Header/><section className="staff-hero live-reveal"><div className="eyebrow"><MapPin size={14}/> STATION CONTROL</div><h1>{data?.location_name || 'Loading station...'}</h1><button className="icon-refresh" onClick={load}><RefreshCw size={16}/> Refresh</button></section>{error && <div className="toast toast-error">{error}</div>}{data && <section className="station-qr live-reveal"><div className="eyebrow"><MapPin size={14}/> STATION QR</div><h2>Let teams scan here.</h2><p>One station QR works for every team at this location. The server accepts it only for a team currently assigned here.</p>{qr && <img src={qr} alt={`QR code for ${data.location_name}`} />}</section>}<section className="station-list live-reveal">{data?.teams.map(team => <article key={`${team.team_identifier}-${team.checkpoint}`} className={`team-card ${team.is_current ? 'current' : ''}`}><div><b>{team.team_identifier}</b><span>{team.team_name}</span></div><div className="team-meta"><em>R1.{team.checkpoint}</em><strong>SET {team.set}</strong></div><small>{team.complete ? 'Completed' : team.scanned ? 'Scanned · envelope active' : team.is_current ? 'Expected now' : 'Expected later'} · {team.attempts}/3{team.last_answer !== null ? ` · last answer: ${team.last_answer}` : ''}</small></article>)}</section></main></LiveShell>;
}

export function SuperAdminPage() {
  const [data, setData] = useState<Control | null>(null); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const [selected, setSelected] = useState<ControlTeam | null>(null); const [resetOpen, setResetOpen] = useState(false); const [action, setAction] = useState<'UNLOCK' | 'MARK_CORRECT'>('UNLOCK'); const [password, setPassword] = useState(''); const [reason, setReason] = useState(''); const [resetPassword, setResetPassword] = useState(''); const [resetPasswordConfirmation, setResetPasswordConfirmation] = useState(''); const [resetReason, setResetReason] = useState(''); const nav = useNavigate();
  const load = () => request<Control>('/control/overview').then(setData).catch(item => setError(item.message));
  useEffect(() => { if (getSession()?.role !== 'SUPER_ADMIN') nav('/login', { replace: true }); else void load(); }, []);
  async function start() { setBusy(true); try { await request('/control/start', 'POST', {}); await load(); } catch (item) { setError(item instanceof Error ? item.message : 'Unable to start.'); } finally { setBusy(false); } }
  async function override(event: FormEvent) { event.preventDefault(); if (!selected) return; setBusy(true); setError(''); try { await request('/control/override', 'POST', { team_identifier: selected.team_identifier, action, password, reason }); setSelected(null); setPassword(''); setReason(''); await load(); } catch (item) { setError(item instanceof Error ? item.message : 'Override failed.'); } finally { setBusy(false); } }
  async function reset(event: FormEvent) { event.preventDefault(); if (resetPassword !== resetPasswordConfirmation) { setError('The two reset password entries do not match.'); return; } if (!window.confirm('Are you absolutely sure? This clears all Round 1 scans, answers, times, finish order, and Secret Agent names.')) return; setBusy(true); setError(''); try { await request('/control/reset', 'POST', { password: resetPassword, password_confirmation: resetPasswordConfirmation, confirmed: true, reason: resetReason }); setResetOpen(false); setResetPassword(''); setResetPasswordConfirmation(''); setResetReason(''); await load(); } catch (item) { setError(item instanceof Error ? item.message : 'Round reset failed.'); } finally { setBusy(false); } }
  async function exportReport() { setBusy(true); setError(''); try { await downloadReportPdf(); } catch (item) { setError(item instanceof Error ? item.message : 'PDF export failed.'); } finally { setBusy(false); } }
  return <LiveShell><main className="mobile-page"><Header/><section className="staff-hero live-reveal"><div className="eyebrow"><ShieldCheck size={14}/> SUPER ADMIN</div><h1>Round 01 <span>control.</span></h1><p>{data?.started ? 'The event is live.' : 'The event has not started.'}</p>{!data?.started && <button className="primary-button" onClick={start} disabled={busy}><Play size={17}/>{busy ? 'Starting...' : 'Start round'}</button>}<button className="icon-refresh" onClick={load}><RefreshCw size={16}/> Refresh live status</button><button className="icon-refresh" onClick={exportReport} disabled={busy}><Download size={16}/> Download verification PDF</button><button className="danger-button" type="button" onClick={() => { setResetOpen(true); setError(''); }}><RotateCcw size={16}/> Reset Round 1</button></section>{error && <div className="toast toast-error">{error}</div>}<section className="control-summary live-reveal"><div><Users size={18}/><strong>{data?.teams.length || 0}</strong><span>teams</span></div><div><MapPin size={18}/><strong>{data?.qualified_count || 0}/{data?.qualifier_limit || 16}</strong><span>qualified</span></div></section>
  {resetOpen && <section className="override-card reset-card live-reveal"><button className="close-button" type="button" onClick={() => setResetOpen(false)} aria-label="Close reset"><X size={17}/></button><div className="eyebrow"><RotateCcw size={14}/> DESTRUCTIVE ACTION</div><h2>Reset all of Round 1?</h2><p>This clears every QR scan, answer, finish time, qualification order, and Secret Agent record. Team IDs, passwords, points base, and routes remain unchanged.</p><form onSubmit={reset}><label>Reason for reset<input value={resetReason} onChange={event => setResetReason(event.target.value)} minLength={3} required placeholder="Testing complete" /></label><label>Enter your password<input value={resetPassword} onChange={event => setResetPassword(event.target.value)} type="password" required autoComplete="current-password" /></label><label>Enter your password again<input value={resetPasswordConfirmation} onChange={event => setResetPasswordConfirmation(event.target.value)} type="password" required autoComplete="current-password" /></label><button className="danger-button reset-submit" disabled={busy}>{busy ? 'Resetting...' : <>Reset Round 1 <RotateCcw size={16}/></>}</button></form></section>}
  {selected && <section className="override-card live-reveal"><button className="close-button" type="button" onClick={() => setSelected(null)} aria-label="Close override"><X size={17}/></button><div className="eyebrow"><ShieldCheck size={14}/> MANUAL ACCESS</div><h2>{selected.team_identifier}</h2><p>Use only after confirming the physical issue with event staff. Every override is logged with your ID and reason.</p><form onSubmit={override}><div className="action-toggle"><button type="button" className={action === 'UNLOCK' ? 'active' : ''} onClick={() => setAction('UNLOCK')}><Unlock size={15}/> Unlock attempts</button><button type="button" className={action === 'MARK_CORRECT' ? 'active' : ''} onClick={() => setAction('MARK_CORRECT')}><CheckCircle2 size={15}/> Mark correct</button></div><label>Reason<input value={reason} onChange={event => setReason(event.target.value)} minLength={3} required placeholder="Explain the decision" /></label><label>Confirm your password<input value={password} onChange={event => setPassword(event.target.value)} type="password" required autoComplete="current-password" /></label><button className="primary-button" disabled={busy}>{busy ? 'Saving...' : 'Confirm override'}</button></form></section>}
  <section className="station-list live-reveal">{data?.teams.map(team => <button type="button" className={`team-card team-select ${team.qualified ? 'qualified' : ''}`} key={team.team_identifier} onClick={() => { setSelected(team); setAction('UNLOCK'); setError(''); }}><div><b>{team.team_identifier}</b><span>{team.team_name}</span></div><div className="team-meta"><em>{team.complete ? team.qualified ? `#${team.rank} QUALIFIED` : `#${team.rank} FINISHED` : `R1.${team.checkpoint}`}</em><strong>{team.complete ? stamp(team.completed_at) : `L${team.location} · SET ${team.set}`}</strong></div><small>Points: {team.points} · Secret Agent: {team.secret_agent_name || 'Not submitted'} · {team.complete ? `Finished ${stamp(team.completed_at)}` : `${team.attempts}/3 attempts`}{team.last_answer !== null ? ` · last: ${team.last_answer}` : ''}</small></button>)}</section></main></LiveShell>;
}
